#!/usr/bin/env python3
"""config/leg_table.yaml from sim/model/leg_map.py (the four-bar leg): crank theta -> leg joint value h
(= motor-axle height - wheel radius, the wbctrl 'h') and dh/dtheta. The C++ node interpolates it."""
import math
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '../../../sim/model'))
import leg_map  # noqa: E402

th = np.linspace(leg_map.THETA_MIN, leg_map.THETA_MAX, 241)
h = np.array([leg_map.h_of_theta(t) for t in th]) - leg_map.R_WHEEL
dh = np.array([leg_map.dh_dtheta(t) for t in th])
assert np.all(np.diff(h) > 0)
out = os.path.join(HERE, '../config/leg_table.yaml')
with open(out, 'w') as f:
    f.write('# generated by scripts/make_leg_table.py from sim/model/leg_map.py — do not edit\n')
    f.write(f'# wheel radius {leg_map.R_WHEEL} m, theta0 (CAD zero, M = 0) = 45.002 deg\n')
    f.write('/**:\n  ros__parameters:\n    leg_table:\n')
    f.write(f'      r_wheel: {leg_map.R_WHEEL}\n      theta0_deg: 45.002\n')
    for name, arr in (('theta_rad', th), ('h_m', h), ('dh_dtheta', dh)):
        f.write(f'      {name}: [' + ', '.join(f'{v:.7f}' for v in arr) + ']\n')
print(f'{out}: theta {math.degrees(th[0]):.2f}..{math.degrees(th[-1]):.2f} deg, h {h[0]:.4f}..{h[-1]:.4f} m')
